/*
 * @Descripttion: 
 * @version: 
 * @Author: donghang
 * @Date: 2019-08-28 23:25:07
 * @LastEditors: donghang
 * @LastEditTime: 2019-08-29 07:56:05
 */
#ifndef COLOR_H_
#define COLOR_H_
#define RED                         0xFF0000
#define CYAN                        0x00FFFF 
#define BLUE	                    0x0000FF 
#define DARKBLUE	                0x0000A0
#define LIGHTBLUE	                0xADD8E6	
#define ORANGE	                    0xFFA500
#define PURPLE	                    0x800080	
#define BROWN	                    0xA52A2A
#define YELLOW	                    0xFFFF00	
// #define MAROON	                    0x800000
#define LIME	                    0x00FF00	
// #define GREEN	                    0x008000
#define MAGENTA	                    0xFF00FF	
#define OLIVE	                    0x808000 
#define BLACK                       0x000000	
#define NIGHT                       0x0C090A	
#define GUNMETAL                    0x2C3539	
#define MIDNIGHT                    0x2B1B17	
#define CHARCOAL                    0x34282C	
#define DARK_SLATE_GREY             0x25383C	
#define OIL                         0x3B3131	
#define BLACK_CAT                   0x413839	
#define IRIDIUM                     0x3D3C3A	
#define BLACK_EEL                   0x463E3F	
#define BLACK_COW                   0x4C4646	
#define GRAY_WOLF                   0x504A4B	
#define VAMPIRE_GRAY                0x565051	
#define GRAY_DOLPHIN                0x5C5858
#define CARBON_GRAY                 0x625D5D	
#define ASH_GRAY                    0x666362	
#define CLOUDY_GRAY                 0x6D6968	
#define SMOKEY_GRAY                 0x726E6D	
#define GRAY                        0x736F6E	
#define GRANITE                     0x837E7C	
#define BATTLESHIP_GRAY             0x848482	
#define GRAY_CLOUD                  0xB6B6B4	
#define GRAY_GOOSE                  0xD1D0CE	
#define PLATINUM                    0xE5E4E2	
#define METALLIC_SILVER             0xBCC6CC	
#define BLUE_GRAY                   0x98AFC7	
#define LIGHT_SLATE_GRAY            0x6D7B8D	
#define SLATE_GRAY                  0x657383	
#define JET_GRAY                    0x616D7E	
#define MIST_BLUE                   0x646D7E	
#define MARBLE_BLUE                 0x566D7E	
// #define SLATE_BLUE                  0x737CA1	
#define STEEL_BLUE                  0x4863A0	
#define BLUE_JAY                    0x2B547E	
#define DARK_SLATE_BLUE             0x2B3856	
#define MIDNIGHT_BLUE               0x151B54	
#define NAVY_BLUE                   0x000080	
#define BLUE_WHALE                  0x342D7E	
#define LAPIS_BLUE                  0x15317E	
#define CORNFLOWER_BLUE             0x151B8D	
#define EARTH_BLUE                  0x0000A0	
#define COBALT_BLUE                 0x0020C2	
#define BLUEBERRY_BLUE              0x0041C2	
#define SAPPHIRE_BLUE               0x2554C7	
#define BLUE_EYES                   0x1569C7	
#define ROYAL_BLUE                  0x2B60DE	
#define BLUE_ORCHID                 0x1F45FC	
#define BLUE_LOTUS                  0x6960EC
#define LIGHT_SLATE_BLUE            0x736AFF	
#define SLATE_BLUE                  0x357EC7	
#define GLACIAL_BLUE_ICE            0x368BC1	
#define SILK_BLUE                   0x488AC7	
#define BLUE_IVY                    0x3090C7	
#define BLUE_KOI                    0x659EC7	
#define COLUMBIA_BLUE               0x87AFC7	
#define BABY_BLUE                   0x95B9C7	
#define LIGHT_STEEL_BLUE            0x728FCE	
#define OCEAN_BLUE                  0x2B65EC	
#define BLUE_RIBBON                 0x306EFF	
#define BLUE_DRESS                  0x157DEC	
#define DODGER_BLUE                 0x1589FF	
// #define CORNFLOWER_BLUE             0x6495ED	
#define SKY_BLUE                    0x6698FF	
#define BUTTERFLY_BLUE              0x38ACEC	
#define ICEBERG                     0x56A5EC
#define CRYSTAL_BLUE                0x5CB3FF	
#define DEEP_SKY_BLUE               0x3BB9FF	
#define DENIM_BLUE                  0x79BAEC	
#define LIGHT_SKY_BLUE              0x82CAFA	
#define DAY_SKY_BLUE                0x82CAFF	
#define JEANS_BLUE                  0xA0CFEC	
#define BLUE_ANGEL                  0xB7CEEC	
#define PASTEL_BLUE                 0xB4CFEC	
#define SEA_BLUE                    0xC2DFFF	
#define POWDER_BLUE                 0xC6DEFF	
#define CORAL_BLUE                  0xAFDCEC   
#define LIGHT_BLUE                  0xADDFFF	
#define ROBIN_EGG_BLUE              0xBDEDFF	
#define PALE_BLUE_LILY              0xCFECEC	
#define LIGHT_CYAN                  0xE0FFFF	
#define WATER                       0xEBF4FA	
#define ALICEBLUE                   0xF0F8FF	
#define AZURE                       0xF0FFFF	
#define LIGHT_SLATE                 0xCCFFFF	
#define LIGHT_AQUAMARINE            0x93FFE8	
#define ELECTRIC_BLUE               0x9AFEFF	
#define AQUAMARINE                  0x7FFFD4	
#define CYAN_OR_AQUA                0x00FFFF	
#define TRON_BLUE                   0x7DFDFE	
#define BLUE_ZIRCON                 0x57FEFF	
#define BLUE_LAGOON                 0x8EEBEC	
#define CELESTE                     0x50EBEC	
#define BLUE_DIAMOND                0x4EE2EC	
#define TIFFANY_BLUE                0x81D8D0	
#define CYAN_OPAQUE                 0x92C7C7	
#define BLUE_HOSTA                  0x77BFC7	
#define NORTHERN_LIGHTS_BLUE        0x78C7C7	
#define MEDIUM_TURQUOISE            0x48CCCD	
#define TURQUOISE                   0x43C6DB	
#define JELLYFISH                   0x46C7C7	
#define MACAW_BLUE_GREEN            0x43BFC7	
#define LIGHT_SEA_GREEN             0x3EA99F	
#define DARK_TURQUOISE              0x3B9C9C	
#define SEA_TURTLE_GREEN            0x438D80	
#define MEDIUM_AQUAMARINE           0x348781	
#define GREENISH_BLUE               0x307D7E	
#define GRAYISH_TURQUOISE           0x5E7D7E	
#define BEETLE_GREEN                0x4C787E	
#define TEAL                        0x008080	
#define SEA_GREEN                   0x4E8975	
#define CAMOUFLAGE_GREEN            0x78866B	
#define SAGE_GREEN                  0x848B79	
#define HAZEL_GREEN                 0x617C58	
#define VENOM_GREEN                 0x728C00	
#define FERN_GREEN                  0x667C26	
#define DARK_FOREST_GREEN           0x254117	
#define MEDIUM_SEA_GREEN            0x306754	
#define MEDIUM_FOREST_GREEN         0x347235	
#define SEAWEED_GREEN               0x437C17	
#define PINE_GREEN                  0x387C44	
#define JUNGLE_GREEN                0x347C2C	
#define SHAMROCK_GREEN              0x347C17	
#define MEDIUM_SPRING_GREEN         0x348017	
#define FOREST_GREEN                0x4E9258	
#define GREEN_ONION                 0x6AA121	
#define SPRING_GREEN                0x4AA02C	
#define LIME_GREEN                  0x41A317	
#define CLOVER_GREEN                0x3EA055	
#define GREEN_SNAKE                 0x6CBB3C	
#define ALIEN_GREEN                 0x6CC417	
#define GREEN_APPLE                 0x4CC417	
#define YELLOW_GREEN                0x52D017	
#define KELLY_GREEN                 0x4CC552	
#define ZOMBIE_GREEN                0x54C571	
#define FROG_GREEN                  0x99C68E	
#define GREEN_PEAS                  0x89C35C	
#define DOLLAR_BILL_GREEN           0x85BB65	
#define DARK_SEA_GREEN              0x8BB381	
#define IGUANA_GREEN                0x9CB071	
#define AVOCADO_GREEN               0xB2C248	
#define PISTACHIO_GREEN             0x9DC209	
#define SALAD_GREEN                 0xA1C935	
#define HUMMINGBIRD_GREEN           0x7FE817	
#define NEBULA_GREEN                0x59E817	
#define STOPLIGHT_GO_GREEN          0x57E964	
#define ALGAE_GREEN                 0x64E986	
#define JADE_GREEN                  0x5EFB6E	
#define GREEN                       0x00FF00	
#define EMERALD_GREEN               0x5FFB17	
#define LAWN_GREEN                  0x87F717	
#define CHARTREUSE                  0x8AFB17	
#define DRAGON_GREEN                0x6AFB92	
#define MINT_GREEN                  0x98FF98	
#define GREEN_THUMB                 0xB5EAAA	
#define LIGHT_JADE                  0xC3FDB8	
#define TEA_GREEN                   0xCCFB5D	
#define GREEN_YELLOW                0xB1FB17	
#define SLIME_GREEN                 0xBCE954	
#define GOLDENROD                   0xEDDA74	
#define HARVEST_GOLD                0xEDE275	
#define SUN_YELLOW                  0xFFE87C	
#define YELLOW                      0xFFFF00	
#define CORN_YELLOW                 0xFFF380	
#define PARCHMENT                   0xFFFFC2	
#define CREAM                       0xFFFFCC	
#define LEMON_CHIFFON               0xFFF8C6	
#define CORNSILK                    0xFFF8DC	
#define BEIGE                       0xF5F5DC	
#define BLONDE                      0xFBF6D9	
#define ANTIQUEWHITE                0xFAEBD7	
#define CHAMPAGNE                   0xF7E7CE	
#define BLANCHEDALMOND              0xFFEBCD	
#define VANILLA                     0xF3E5AB	
#define TAN_BROWN                   0xECE5B6	
#define PEACH                       0xFFE5B4	
#define MUSTARD                     0xFFDB58	
#define RUBBER_DUCKY_YELLOW         0xFFD801	
#define BRIGHT_GOLD                 0xFDD017	
#define GOLDEN_BROWN                0xEAC117	
#define MACARONI_AND_CHEESE         0xF2BB66	
#define SAFFRON                     0xFBB917	
#define BEER                        0xFBB117	
#define CANTALOUPE                  0xFFA62F	
#define BEE_YELLOW                  0xE9AB17	
#define BROWN_SUGAR                 0xE2A76F	
#define BURLYWOOD                   0xDEB887	
#define DEEP_PEACH                  0xFFCBA4	
#define GINGER_BROWN                0xC9BE62	
#define SCHOOL_BUS_YELLOW           0xE8A317	
#define SANDY_BROWN                 0xEE9A4D	
#define FALL_LEAF_BROWN             0xC8B560	
#define ORANGE_GOLD                 0xD4A017	
#define SAND                        0xC2B280	
#define COOKIE_BROWN                0xC7A317	
#define CARAMEL                     0xC68E17	
#define BRASS                       0xB5A642	
#define KHAKI                       0xADA96E	
#define CAMEL_BROWN                 0xC19A6B	
#define BRONZE                      0xCD7F32	
#define TIGER_ORANGE                0xC88141	
#define CINNAMON                    0xC58917	
#define BULLET_SHELL                0xAF9B60	
#define DARK_GOLDENROD              0xAF7817	
#define COPPER                      0xB87333	
#define WOOD                        0x966F33	
#define OAK_BROWN                   0x806517	
#define MOCCASIN                    0x827839	
#define ARMY_BROWN                  0x827B60	
#define SANDSTONE                   0x786D5F	
#define MOCHA                       0x493D26	
#define TAUPE                       0x483C32	
#define COFFEE                      0x6F4E37	
#define BROWN_BEAR                  0x835C3B	
#define RED_DIRT                    0x7F5217	
#define SEPIA                       0x7F462C	
#define ORANGE_SALMON               0xC47451	
#define RUST                        0xC36241	
#define RED_FOX                     0xC35817	
#define CHOCOLATE                   0xC85A17	
#define SEDONA                      0xCC6600	
#define PAPAYA_ORANGE               0xE56717	
#define HALLOWEEN_ORANGE            0xE66C2C	
#define PUMPKIN_ORANGE              0xF87217	
#define CONSTRUCTION_CONE_ORANGE    0xF87431	
#define SUNRISE_ORANGE              0xE67451	
#define MANGO_ORANGE                0xFF8040	
#define DARK_ORANGE                 0xF88017	
#define CORAL                       0xFF7F50	
#define BASKET_BALL_ORANGE          0xF88158	
#define LIGHT_SALMON                0xF9966B
#define TANGERINE                   0xE78A61
#define DARK_SALMON                 0xE18B6B	
#define LIGHT_CORAL                 0xE77471	
#define BEAN_RED                    0xF75D59	
#define VALENTINE_RED               0xE55451	
#define SHOCKING_ORANGE             0xE55B3C	
#define RED                         0xFF0000	
#define SCARLET                     0xFF2400	
#define RUBY_RED                    0xF62217	
#define FERRARI_RED                 0xF70D1A	
#define FIRE_ENGINE_RED             0xF62817	
#define LAVA_RED                    0xE42217	
#define LOVE_RED                    0xE41B17	
#define GRAPEFRUIT                  0xDC381F	
#define CHESTNUT_RED                0xC34A2C	
#define CHERRY_RED                  0xC24641	
#define MAHOGANY                    0xC04000	
#define CHILLI_PEPPER               0xC11B17	
#define CRANBERRY                   0x9F000F	
#define RED_WINE                    0x990012	
#define BURGUNDY                    0x8C001A	
#define CHESTNUT                    0x954535	
#define BLOOD_RED                   0x7E3517	
#define SIENNA                      0x8A4117	
#define SANGRIA                     0x7E3817	
#define FIREBRICK                   0x800517	
#define MAROON                      0x810541	
#define PLUM_PIE                    0x7D0541	
#define VELVET_MAROON               0x7E354D	
#define PLUM_VELVET                 0x7D0552	
#define ROSY_FINCH                  0x7F4E52	
#define PUCE                        0x7F5A58	
#define DULL_PURPLE                 0x7F525D	
#define ROSY_BROWN                  0xB38481	
#define KHAKI_ROSE                  0xC5908E	
#define PINK_BOW                    0xC48189	
#define LIPSTICK_PINK               0xC48793	
#define ROSE                        0xE8ADAA	
#define DESERT_SAND                 0xEDC9AF	
#define PIG_PINK                    0xFDD7E4	
#define COTTON_CANDY                0xFCDFFF	
#define PINK_BUBBLEGUM              0xFFDFDD	
#define MISTY_ROSE                  0xFBBBB9	
#define PINK                        0xFAAFBE	
#define LIGHT_PINK                  0xFAAFBA	
#define FLAMINGO_PINK               0xF9A7B0	
#define PINK_ROSE                   0xE7A1B0	
#define PINK_DAISY                  0xE799A3	
#define CADILLAC_PINK               0xE38AAE	
// #define CARNATION_PINK              0xF778A1	
#define BLUSH_RED                   0xE56E94	
#define HOT_PINK                    0xF660AB	
#define WATERMELON_PINK             0xFC6C85	
#define VIOLET_RED                  0xF6358A	
#define DEEP_PINK                   0xF52887	
#define PINK_CUPCAKE                0xE45E9D	
#define PINK_LEMONADE               0xE4287C	
#define NEON_PINK                   0xF535AA	
#define MAGENTA                     0xFF00FF	
#define DIMORPHOTHECA_MAGENTA       0xE3319D	
#define BRIGHT_NEON_PINK            0xF433FF	
#define PALE_VIOLET_RED             0xD16587	
#define TULIP_PINK                  0xC25A7C	
#define MEDIUM_VIOLET_RED           0xCA226B	
#define ROGUE_PINK                  0xC12869	
#define BURNT_PINK                  0xC12267	
#define BASHFUL_PINK                0xC25283	
#define CARNATION_PINK              0xC12283	
#define PLUM                        0xB93B8F	
#define VIOLA_PURPLE                0x7E587E	
#define PURPLE_IRIS                 0x571B7E	
#define PLUM_PURPLE                 0x583759
#define INDIGO                      0x4B0082	
#define PURPLE_MONSTER              0x461B7E	
#define PURPLE_HAZE                 0x4E387E	
#define EGGPLANT                    0x614051	
#define GRAPE                       0x5E5A80	
#define PURPLE_JAM                  0x6A287E	
#define DARK_ORCHID                 0x7D1B7E	
#define PURPLE_FLOWER               0xA74AC7	
#define MEDIUM_ORCHID               0xB048B5	
#define PURPLE_AMETHYST             0x6C2DC7	
#define DARK_VIOLET                 0x842DCE	
#define VIOLET                      0x8D38C9	
#define PURPLE_SAGE_BUSH            0x7A5DC7	
#define LOVELY_PURPLE               0x7F38EC	
// #define PURPLE                      0x8E35EF	
#define AZTECH_PURPLE               0x893BFF	
#define MEDIUM_PURPLE               0x8467D7	
#define JASMINE_PURPLE              0xA23BEC	
#define PURPLE_DAFFODIL             0xB041FF	
#define TYRIAN_PURPLE               0xC45AEC	
#define CROCUS_PURPLE               0x9172EC	
#define PURPLE_MIMOSA               0x9E7BFF	
#define HELIOTROPE_PURPLE           0xD462FF	
#define CRIMSON                     0xE238EC	
#define PURPLE_DRAGON               0xC38EC7	
#define LILAC                       0xC8A2C8	
#define BLUSH_PINK                  0xE6A9EC	
#define MAUVE                       0xE0B0FF	
#define WISTERIA_PURPLE             0xC6AEC7	
#define BLOSSOM_PINK                0xF9B7FF	
#define THISTLE                     0xD2B9D3	
#define PERIWINKLE                  0xE9CFEC	
#define LAVENDER_PINOCCHIO          0xEBDDE2	
#define LAVENDER_BLUE               0xE3E4FA	
#define PEARL                       0xFDEEF4	
#define SEASHELL                    0xFFF5EE	
#define MILK_WHITE                  0xFEFCFF	
#define White                       0xFFFFFF	 
#endif